# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `annotate` gem.
# Please instead update this file by running `bin/tapioca gem annotate`.

module Annotate
  class << self
    def bootstrap_rake; end
    def eager_load(options); end
    def fallback(*args); end
    def load_requires(options); end
    def load_tasks; end
    def loaded_tasks; end
    def loaded_tasks=(val); end

    # Set default values that can be overridden via environment variables.
    def set_defaults(options = T.unsafe(nil)); end

    def setup_options(options = T.unsafe(nil)); end
    def skip_on_migration?; end
    def true?(val); end
    def version; end
  end
end

Annotate::FLAG_OPTIONS = T.let(T.unsafe(nil), Array)
Annotate::OTHER_OPTIONS = T.let(T.unsafe(nil), Array)
Annotate::PATH_OPTIONS = T.let(T.unsafe(nil), Array)

# The set of available options to customize the behavior of Annotate.
Annotate::POSITION_OPTIONS = T.let(T.unsafe(nil), Array)

Annotate::TRUE_RE = T.let(T.unsafe(nil), Regexp)

module AnnotateModels
  class << self
    # Given the name of an ActiveRecord class, create a schema
    # info block (basically a comment containing information
    # on the columns and their types) and put it at the front
    # of the model and fixture source files.
    # Returns true or false depending on whether the source
    # files were modified.
    #
    # === Options (opts)
    # :position_in_class<Symbol>:: where to place the annotated section in model file
    # :position_in_test<Symbol>:: where to place the annotated section in test/spec file(s)
    # :position_in_fixture<Symbol>:: where to place the annotated section in fixture file
    # :position_in_factory<Symbol>:: where to place the annotated section in factory file
    # :exclude_tests<Symbol>:: whether to skip modification of test/spec files
    # :exclude_fixtures<Symbol>:: whether to skip modification of fixture files
    # :exclude_factories<Symbol>:: whether to skip modification of factory files
    def annotate(klass, file, header, options = T.unsafe(nil)); end

    def annotate_model_file(annotated, file, header, options); end

    # Add a schema block to a file. If the file already contains
    # a schema info block (a comment starting with "== Schema Information"), check if it
    # matches the block that is already there. If so, leave it be. If not, remove the old
    # info block and write a new one.
    # Returns true or false depending on whether the file was modified.
    #
    # === Options (opts)
    # :force<Symbol>:: whether to update the file even if it doesn't seem to need it.
    # :position_in_*<Symbol>:: where to place the annotated section in fixture or model file,
    # :before or :after. Default is :before.
    def annotate_one_file(file_name, info_block, position, options = T.unsafe(nil)); end

    # We're passed a name of things that might be
    # ActiveRecord models. If we can find the class, and
    # if its a subclass of ActiveRecord::Base,
    # then pass it to the associated block
    def do_annotations(options = T.unsafe(nil)); end

    def get_index_info(klass, options = T.unsafe(nil)); end

    # Retrieve loaded model class by path to the file where it's supposed to be defined.
    def get_loaded_model(model_path); end

    # Retrieve the classes belonging to the model names we're asked to process
    # Check for namespaced models in subdirectories as well as models
    # in subdirectories without namespacing.
    def get_model_class(file); end

    # Return a list of the model files to annotate. If we have
    # command line arguments, they're assumed to be either
    # the underscore or CamelCase versions of model names.
    # Otherwise we take all the model files in the
    # model_dir directory.
    def get_model_files(options); end

    # Use the column information in an ActiveRecord class
    # to create a comment block containing a line for
    # each column. The line contains the column name,
    # the type (and length), and any optional attributes
    def get_schema_info(klass, header, options = T.unsafe(nil)); end

    def model_dir; end
    def model_dir=(dir); end

    # position = :position_in_fixture or :position_in_class
    def options_with_position(options, position_in); end

    # Simple quoting for the default column value
    def quote(value); end

    def remove_annotation_of_file(file_name); end
    def remove_annotations(options = T.unsafe(nil)); end
    def resolve_filename(filename_template, model_name, table_name); end
  end
end

AnnotateModels::BLUEPRINTS_SPEC_DIR = T.let(T.unsafe(nil), String)

# Machinist http://github.com/notahat/machinist
AnnotateModels::BLUEPRINTS_TEST_DIR = T.let(T.unsafe(nil), String)

# Annotate Models plugin use this header
AnnotateModels::COMPAT_PREFIX = T.let(T.unsafe(nil), String)

AnnotateModels::COMPAT_PREFIX_MD = T.let(T.unsafe(nil), String)
AnnotateModels::END_MARK = T.let(T.unsafe(nil), String)
AnnotateModels::EXEMPLARS_SPEC_DIR = T.let(T.unsafe(nil), String)

# Object Daddy http://github.com/flogic/object_daddy/tree/master
AnnotateModels::EXEMPLARS_TEST_DIR = T.let(T.unsafe(nil), String)

AnnotateModels::FABRICATORS_SPEC_DIR = T.let(T.unsafe(nil), String)

# Fabrication https://github.com/paulelliott/fabrication.git
AnnotateModels::FABRICATORS_TEST_DIR = T.let(T.unsafe(nil), String)

AnnotateModels::FACTORY_GIRL_SPEC_DIR = T.let(T.unsafe(nil), String)

# Factory Girl http://github.com/thoughtbot/factory_girl
AnnotateModels::FACTORY_GIRL_TEST_DIR = T.let(T.unsafe(nil), String)

AnnotateModels::FACTORY_PATTERNS = T.let(T.unsafe(nil), Array)
AnnotateModels::FIXTURE_PATTERNS = T.let(T.unsafe(nil), Array)
AnnotateModels::FIXTURE_SPEC_DIR = T.let(T.unsafe(nil), String)
AnnotateModels::FIXTURE_TEST_DIR = T.let(T.unsafe(nil), String)

# since rails 4.0
AnnotateModels::MODEL_TEST_DIR = T.let(T.unsafe(nil), String)

# Don't show limit (#) on these column types
# Example: show "integer" instead of "integer(4)"
AnnotateModels::NO_LIMIT_COL_TYPES = T.let(T.unsafe(nil), Array)

AnnotateModels::PATTERN = T.let(T.unsafe(nil), Regexp)
AnnotateModels::PREFIX = T.let(T.unsafe(nil), String)
AnnotateModels::PREFIX_MD = T.let(T.unsafe(nil), String)
AnnotateModels::SPEC_MODEL_DIR = T.let(T.unsafe(nil), String)
AnnotateModels::TEST_PATTERNS = T.let(T.unsafe(nil), Array)

# File.join for windows reverse bar compat?
# I dont use windows, can`t test
AnnotateModels::UNIT_TEST_DIR = T.let(T.unsafe(nil), String)

module AnnotateRoutes
  class << self
    def do_annotations(options = T.unsafe(nil)); end
    def remove_annotations(options = T.unsafe(nil)); end
    def routes_exists?; end
    def routes_file; end
    def strip_annotations(content); end
    def strip_on_removal(content, where_header_found); end
    def write_contents(content); end
  end
end

AnnotateRoutes::PREFIX = T.let(T.unsafe(nil), String)
