# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `graphiql-rails` gem.
# Please instead update this file by running `bin/tapioca gem graphiql-rails`.

module GraphiQL; end

module GraphiQL::Rails
  class << self
    # Returns the value of attribute config.
    def config; end

    # Sets the attribute config
    def config=(_arg0); end

    def railtie_helpers_paths; end
    def railtie_namespace; end
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end
    def table_name_prefix; end
    def use_relative_model_naming?; end
  end
end

class GraphiQL::Rails::Config
  def initialize(query_params: T.unsafe(nil), initial_query: T.unsafe(nil), title: T.unsafe(nil), logo: T.unsafe(nil), csrf: T.unsafe(nil), headers: T.unsafe(nil)); end

  # Returns the value of attribute csrf.
  def csrf; end

  # Sets the attribute csrf
  def csrf=(_arg0); end

  def headers; end
  def headers=(_arg0); end

  # Returns the value of attribute initial_query.
  def initial_query; end

  # Sets the attribute initial_query
  def initial_query=(_arg0); end

  # Returns the value of attribute logo.
  def logo; end

  # Sets the attribute logo
  def logo=(_arg0); end

  # Returns the value of attribute query_params.
  def query_params; end

  # Sets the attribute query_params
  def query_params=(_arg0); end

  # Call defined procs, add CSRF token if specified
  def resolve_headers(view_context); end

  # Returns the value of attribute title.
  def title; end

  # Sets the attribute title
  def title=(_arg0); end
end

GraphiQL::Rails::Config::CSRF_TOKEN_HEADER = T.let(T.unsafe(nil), Hash)
GraphiQL::Rails::Config::DEFAULT_HEADERS = T.let(T.unsafe(nil), Hash)
class GraphiQL::Rails::Engine < ::Rails::Engine; end
GraphiQL::Rails::VERSION = T.let(T.unsafe(nil), String)
