# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rgeo-geojson` gem.
# Please instead update this file by running `bin/tapioca gem rgeo-geojson`.

# -----------------------------------------------------------------------------
#
# Well-known text generator for RGeo
#
# -----------------------------------------------------------------------------
module RGeo; end

module RGeo::GeoJSON
  class << self
    # Creates and returns a coder object of type RGeo::GeoJSON::Coder
    # that encapsulates encoding and decoding settings (principally the
    # RGeo::Feature::Factory and the RGeo::GeoJSON::EntityFactory to be
    # used).
    #
    # The geo factory is a required argument. Other options include:
    #
    # [<tt>:geo_factory</tt>]
    #   Specifies the geo factory to use to create geometry objects.
    #   Defaults to the preferred cartesian factory.
    # [<tt>:entity_factory</tt>]
    #   Specifies an entity factory, which lets you override the types
    #   of GeoJSON entities that are created. It defaults to the default
    #   RGeo::GeoJSON::EntityFactory, which generates objects of type
    #   RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
    #   See RGeo::GeoJSON::EntityFactory for more information.
    def coder(opts = T.unsafe(nil)); end

    # High-level convenience routine for decoding an object from GeoJSON.
    # The input may be a JSON hash, a String, or an IO object from which
    # to read the JSON string.
    #
    # Options include:
    #
    # [<tt>:geo_factory</tt>]
    #   Specifies the geo factory to use to create geometry objects.
    #   Defaults to the preferred cartesian factory.
    # [<tt>:entity_factory</tt>]
    #   Specifies an entity factory, which lets you override the types
    #   of GeoJSON entities that are created. It defaults to the default
    #   RGeo::GeoJSON::EntityFactory, which generates objects of type
    #   RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
    #   See RGeo::GeoJSON::EntityFactory for more information.
    def decode(input_, opts = T.unsafe(nil)); end

    # High-level convenience routine for encoding an object as GeoJSON.
    # Pass the object, which may one of the geometry objects specified
    # in RGeo::Feature, or an appropriate GeoJSON wrapper entity such
    # as RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
    #
    # The only option supported is <tt>:entity_factory</tt>, which lets
    # you override the types of GeoJSON entities supported. See
    # RGeo::GeoJSON::EntityFactory for more information. By default,
    # encode supports objects of type RGeo::GeoJSON::Feature and
    # RGeo::GeoJSON::FeatureCollection.
    def encode(object, opts = T.unsafe(nil)); end
  end
end

# This object encapsulates encoding and decoding settings (principally
# the RGeo::Feature::Factory and the RGeo::GeoJSON::EntityFactory to
# be used) so that you can encode and decode without specifying those
# settings every time.
class RGeo::GeoJSON::Coder
  # Create a new coder settings object. The geo factory is passed as
  # a required argument.
  #
  # Options include:
  #
  # [<tt>:geo_factory</tt>]
  #   Specifies the geo factory to use to create geometry objects.
  #   Defaults to the preferred cartesian factory.
  # [<tt>:entity_factory</tt>]
  #   Specifies an entity factory, which lets you override the types
  #   of GeoJSON entities that are created. It defaults to the default
  #   RGeo::GeoJSON::EntityFactory, which generates objects of type
  #   RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
  #   See RGeo::GeoJSON::EntityFactory for more information.
  #
  # @return [Coder] a new instance of Coder
  def initialize(opts = T.unsafe(nil)); end

  # Decode an object from GeoJSON. The input may be a JSON hash, a
  # String, or an IO object from which to read the JSON string.
  # If an error occurs, nil is returned.
  def decode(input); end

  # Encode the given object as GeoJSON. The object may be one of the
  # geometry objects specified in RGeo::Feature, or an appropriate
  # GeoJSON wrapper entity supported by this coder's entity factory.
  #
  # This method returns a JSON object (i.e. a hash). In order to
  # generate a string suitable for transmitting to a service, you
  # will need to JSON-encode it. This is usually accomplished by
  # calling <tt>to_json</tt> on the hash object, if you have the
  # appropriate JSON library installed.
  #
  # Returns nil if nil is passed in as the object.
  def encode(object); end

  # Returns the RGeo::GeoJSON::EntityFactory used to generate GeoJSON
  # wrapper entities.
  def entity_factory; end

  # Returns the RGeo::Feature::Factory used to generate geometry objects.
  def geo_factory; end

  private

  def decode_feature(input); end
  def decode_geometry(input); end
  def decode_geometry_collection(input); end
  def decode_line_string_coords(line_coords); end
  def decode_multi_line_string_coords(multi_line_coords); end
  def decode_multi_point_coords(multi_point_coords); end
  def decode_multi_polygon_coords(multi_polygon_coords); end
  def decode_point_coords(point_coords); end
  def decode_polygon_coords(poly_coords); end
  def encode_feature(object); end
  def encode_geometry(object); end
end

# This is the default entity factory. It creates objects of type
# RGeo::GeoJSON::Feature and RGeo::GeoJSON::FeatureCollection.
# You may create your own entity factory by duck-typing this class.
class RGeo::GeoJSON::EntityFactory
  # Create and return a new feature, given geometry, ID, and
  # properties hash. Note that, per the GeoJSON spec, geometry and/or
  # properties may be nil.
  def feature(geometry, id = T.unsafe(nil), properties = T.unsafe(nil)); end

  # Create and return a new feature collection, given an enumerable
  # of feature objects.
  def feature_collection(features = T.unsafe(nil)); end

  # Returns the geometry associated with the given feature.
  def get_feature_geometry(object); end

  # Returns the ID of the given feature, or nil for no ID.
  def get_feature_id(object); end

  # Returns the properties of the given feature as a hash. Editing
  # this hash does not change the state of the feature.
  def get_feature_properties(object); end

  # Returns true if the given object is a feature created by this
  # entity factory.
  #
  # @return [Boolean]
  def is_feature?(object); end

  # Returns true if the given object is a feature collection created
  # by this entity factory.
  #
  # @return [Boolean]
  def is_feature_collection?(object); end

  # Run Enumerable#map on the features contained in the given feature
  # collection.
  def map_feature_collection(object, &block); end

  class << self
    # Return the singleton instance of EntityFactory.
    def instance; end
  end
end

# This is a GeoJSON wrapper entity that corresponds to the GeoJSON
# "Feature" type. It is an immutable type.
#
# This is the default implementation that is generated by
# RGeo::GeoJSON::EntityFactory. You may replace this implementation
# by writing your own entity factory. Note that an alternate Feature
# implementation need not subclass or even duck-type this class.
# the entity factory mediates all interaction between the GeoJSON
# engine and features.
class RGeo::GeoJSON::Feature
  # Create a feature wrapping the given geometry, with the given ID
  # and properties.
  #
  # @return [Feature] a new instance of Feature
  def initialize(geometry, id = T.unsafe(nil), properties = T.unsafe(nil)); end

  # Two features are equal if their geometries, IDs, and properties
  # are all equal.
  # This method uses the == operator to test geometry equality, which
  # may behave differently than the eql? method.
  def ==(other); end

  # Gets the value of the given named property.
  # Returns nil if the given property is not found.
  def [](key); end

  # Two features are equal if their geometries, IDs, and properties
  # are all equal.
  # This method uses the eql? method to test geometry equality, which
  # may behave differently than the == operator.
  #
  # @return [Boolean]
  def eql?(other); end

  # Returns the ID for this feature, which may be nil.
  def feature_id; end

  # Returns the geometry contained in this feature, which may be nil.
  def geometry; end

  def hash; end
  def inspect; end

  # Gets an array of the known property keys in this feature.
  def keys; end

  # Returns a copy of the properties for this feature.
  def properties; end

  # Gets the value of the given named property.
  # Returns nil if the given property is not found.
  def property(key); end

  def to_s; end
end

# This is a GeoJSON wrapper entity that corresponds to the GeoJSON
# "FeatureCollection" type. It is an immutable type.
#
# This is the default implementation that is generated by
# RGeo::GeoJSON::EntityFactory. You may replace this implementation
# by writing your own entity factory. Note that an alternate
# FeatureCollection implementation need not subclass or even
# duck-type this class. The entity factory mediates all interaction
# between the GeoJSON engine and feature collections.
class RGeo::GeoJSON::FeatureCollection
  include ::Enumerable

  # Create a new FeatureCollection with the given features, which must
  # be provided as an Enumerable.
  #
  # @return [FeatureCollection] a new instance of FeatureCollection
  def initialize(features = T.unsafe(nil)); end

  # Two feature collections are equal if they contain the same
  # features in the same order.
  # This methods uses the == operator to test geometry equality, which
  # may behave differently than the eql? method.
  def ==(other); end

  # Access a feature by index.
  def [](index); end

  # Iterates or returns an iterator for the features.
  def each(&block); end

  # Two feature collections are equal if they contain the same
  # features in the same order.
  # This methods uses the eql? method to test geometry equality, which
  # may behave differently than the == operator.
  #
  # @return [Boolean]
  def eql?(other); end

  def hash; end
  def inspect; end

  # Returns the number of features contained in this collection.
  def size; end

  def to_s; end
end

RGeo::GeoJSON::VERSION = T.let(T.unsafe(nil), String)
RGeo::VERSION = T.let(T.unsafe(nil), String)
