version: "3.9"

services:
  postgres:
    image: postgis/postgis:14-3.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pgweb:
    # profiles: ["tooling"]
    depends_on: ["postgres"]
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432?sslmode=disable

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200

  kibana:
    # profiles: ["tooling"]
    depends_on: ["elasticsearch"]
    image: docker.elastic.co/kibana/kibana:7.10.1
    volumes:
      - kibana:/usr/share/kibana/data
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres: null
  elasticsearch: null
  kibana: null
