app = "openshelter"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[deploy]
  release_command = "bin/release"
  strategy = "canary"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 3
    method = "get"
    path = "/internal/status"
    protocol = "http"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
