# typed: true
# frozen_string_literal: true

require "active_record/connection_adapters/postgresql_adapter"
require "active_support/core_ext/integer/time"
require "bootsnap/setup"
require "bundler/setup"
require "fileutils"
require "graphql_ext"
require "good_job/engine"
require "json"
require "open3"
require "rails/all"
require "rails/test_help"
require "ripper"
require "route_constraints"
require "rubocop"
require "safe_type"
require "socket"
require "sprockets/railtie"
