# typed: true
# frozen_string_literal: true

class AddSecretKeyToShelterSignals < ActiveRecord::Migration[7.0]
  def change
    add_column :shelter_signals, :secret_key, :string
    add_index :shelter_signals, :secret_key, unique: true

    #
    # when migrating "up" (as in applying migrations; not "down" reversing migrations)
    # find all shelter signals where secret_key is nil
    # update nil to new secret key, generated by SecureRandom.hex(12)
    #
    reversible do |dir|
      dir.up do
        ShelterSignal.where(secret_key: nil).find_each do |signal|
          signal.update!(secret_key: SecureRandom.hex(12))
        end
      end
    end
    change_column_null :shelter_signals, :secret_key, false
  end
end
